sudo: false
language: cpp
install:
  - sudo apt-get install libcr-dev mpich2 mpich2-doc
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./mpich/bin/mpirun -np 4 ./sieve_of_eratosthenes


